---
meta:
    description:
        Creates Firehose delivery streams that deliver records to S3/Redshift
    dependencies:
        - firehose-rsc
        - storage
    parameters:
        firehose_resource_function_arn:
            description:
                The ARN of the Lambda function that backs the custom Firehose resource
            value:
                ref:
                    parser: output
                    parameters:
                        layer_name: firehose-rsc
                        output_name: CustomResourceFunctionArn
        s3_delivery:
            description:
                Common settings for all delivery stream(s)
            value:
                bucket_name:
                    ref:
                        parser: output
                        parameters:
                            layer_name: storage
                            output_name: BucketName
                buffer_mbs: 1
                buffer_seconds: 60
                compression: GZIP
        redshift_delivery:
            description:
                Common Redshift delivery settings for all streams
            value:
                cluster_jdbc_url:
                    ref:
                        parser: secret
                        parameters:
                            service: "humilis:s3-delivery:redshift"
                            key: jdbc_url
                copy_options: CSV GZIP
                username:
                    ref:
                        parser: secret
                        parameters:
                            service: "humilis:s3-delivery:redshift"
                            key: username
                password:
                    ref:
                        parser: secret
                        parameters:
                            service: "humilis:s3-delivery:redshift"
                            key: password 
        streams:
            description:
                The names of the streams and the associated S3 prefixes and, 
                optionally, Redshift tables.
            value:
                - name: DeliveryStream
                  prefix: stream/
                  table: "_test.stream"
